# inventory/prod.yml
---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /mnt/c/Users/user/.ssh/yc_ansible
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  children:
    clickhouse:
      hosts:
        ch-01:
          ansible_host: 178.154.247.83

    vector:
      hosts:
        vector-01:
          ansible_host: 178.154.253.25

    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: 178.154.253.91
